apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: affine-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: affine.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: affine-service
                port:
                  number: 80

